dependencies:
  '@rush-temp/shack': 'file:projects/shack.tgz'
  prettier: 1.15.2
  pretty-quick: 1.8.0
  ts-node: 7.0.1
  typescript: 3.1.6
packages:
  /ansi-styles/3.2.1:
    dependencies:
      color-convert: 1.9.3
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha512-VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==
  /arrify/1.0.1:
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-iYUI2iIm84DfkEcoRWhJwVAaSw0=
  /buffer-from/1.1.1:
    dev: false
    resolution:
      integrity: sha512-MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==
  /chalk/2.4.1:
    dependencies:
      ansi-styles: 3.2.1
      escape-string-regexp: 1.0.5
      supports-color: 5.5.0
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha512-ObN6h1v2fTJSmUXoS3nMQ92LbDK9be4TV+6G+omQlGJFdcUX5heKi1LZ1YnRMIgwTLEj3E24bT6tYni50rlCfQ==
  /color-convert/1.9.3:
    dependencies:
      color-name: 1.1.3
    dev: false
    resolution:
      integrity: sha512-QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==
  /color-name/1.1.3:
    dev: false
    resolution:
      integrity: sha1-p9BVi9icQveV3UIyj3QIMcpTvCU=
  /cross-spawn/5.1.0:
    dependencies:
      lru-cache: 4.1.3
      shebang-command: 1.2.0
      which: 1.3.1
    dev: false
    resolution:
      integrity: sha1-6L0O/uWPz/b4+UUQoKVUu/ojVEk=
  /diff/3.5.0:
    dev: false
    engines:
      node: '>=0.3.1'
    resolution:
      integrity: sha512-A46qtFgd+g7pDZinpnwiRJtxbC1hpgf0uzP3iG89scHk0AUC7A1TGxf5OiiOUv/JMZR8GOt8hL900hV0bOy5xA==
  /escape-string-regexp/1.0.5:
    dev: false
    engines:
      node: '>=0.8.0'
    resolution:
      integrity: sha1-G2HAViGQqN/2rjuyzwIAyhMLhtQ=
  /execa/0.8.0:
    dependencies:
      cross-spawn: 5.1.0
      get-stream: 3.0.0
      is-stream: 1.1.0
      npm-run-path: 2.0.2
      p-finally: 1.0.0
      signal-exit: 3.0.2
      strip-eof: 1.0.0
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-2NdrvBtVIX7RkP1t1J08d07PyNo=
  /find-up/2.1.0:
    dependencies:
      locate-path: 2.0.0
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-RdG35QbHF93UgndaK3eSCjwMV6c=
  /get-stream/3.0.0:
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-jpQ9E1jcN1VQVOy+LtsFqhdO3hQ=
  /has-flag/3.0.0:
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-tdRU3CGZriJWmfNGfloH87lVuv0=
  /ignore/3.3.10:
    dev: false
    resolution:
      integrity: sha512-Pgs951kaMm5GXP7MOvxERINe3gsaVjUWFm+UZPSq9xYriQAksyhg0csnS0KXSNRD5NmNdapXEpjxG49+AKh/ug==
  /is-stream/1.1.0:
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-EtSj3U5o4Lec6428hBc66A2RykQ=
  /isexe/2.0.0:
    dev: false
    resolution:
      integrity: sha1-6PvzdNxVb/iUehDcsFctYz8s+hA=
  /locate-path/2.0.0:
    dependencies:
      p-locate: 2.0.0
      path-exists: 3.0.0
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-K1aLJl7slExtnA3pw9u7ygNUzY4=
  /lru-cache/4.1.3:
    dependencies:
      pseudomap: 1.0.2
      yallist: 2.1.2
    dev: false
    resolution:
      integrity: sha512-fFEhvcgzuIoJVUF8fYr5KR0YqxD238zgObTps31YdADwPPAp82a4M8TrckkWyx7ekNlf9aBcVn81cFwwXngrJA==
  /make-error/1.3.5:
    dev: false
    resolution:
      integrity: sha512-c3sIjNUow0+8swNwVpqoH4YCShKNFkMaw6oH1mNS2haDZQqkeZFlHS3dhoeEbKKmJB4vXpJucU6oH75aDYeE9g==
  /minimist/0.0.8:
    dev: false
    resolution:
      integrity: sha1-hX/Kv8M5fSYluCKCYuhqp6ARsF0=
  /minimist/1.2.0:
    dev: false
    resolution:
      integrity: sha1-o1AIsg9BOD7sH7kU9M1d95omQoQ=
  /mkdirp/0.5.1:
    dependencies:
      minimist: 0.0.8
    dev: false
    hasBin: true
    resolution:
      integrity: sha1-MAV0OOrGz3+MR2fzhkjWaX11yQM=
  /mri/1.1.1:
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-haom09ru7t+A3FmEr5XMXKXK2fE=
  /npm-run-path/2.0.2:
    dependencies:
      path-key: 2.0.1
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-NakjLfo11wZ7TLLd8jV7GHFTbF8=
  /p-finally/1.0.0:
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-P7z7FbiZpEEjs0ttzBi3JDNqLK4=
  /p-limit/1.3.0:
    dependencies:
      p-try: 1.0.0
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha512-vvcXsLAJ9Dr5rQOPk7toZQZJApBl2K4J6dANSsEuh6QI41JYcsS/qhTGa9ErIUUgK3WNQoJYvylxvjqmiqEA9Q==
  /p-locate/2.0.0:
    dependencies:
      p-limit: 1.3.0
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-IKAQOyIqcMj9OcwuWAaA893l7EM=
  /p-try/1.0.0:
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-y8ec26+P1CKOE/Yh8rGiN8GyB7M=
  /path-exists/3.0.0:
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-zg6+ql94yxiSXqfYENe1mwEP1RU=
  /path-key/2.0.1:
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-QRyttXTFoUDTpLGRDUDYDMn0C0A=
  /prettier/1.15.2:
    dev: false
    engines:
      node: '>=4'
    hasBin: true
    resolution:
      integrity: sha512-YgPLFFA0CdKL4Eg2IHtUSjzj/BWgszDHiNQAe0VAIBse34148whfdzLagRL+QiKS+YfK5ftB6X4v/MBw8yCoug==
  /pretty-quick/1.8.0:
    dependencies:
      chalk: 2.4.1
      execa: 0.8.0
      find-up: 2.1.0
      ignore: 3.3.10
      mri: 1.1.1
    dev: false
    hasBin: true
    peerDependencies:
      prettier: '>=1.8.0'
    resolution:
      integrity: sha512-qV25sQF/ivJpdZ5efwemQYkQJa7sp3HqT/Vf/7z5vGYMcq1VrT2lDpFKAxJPf6219N1YAdR8mGkIhPAZ1odTmQ==
  /pseudomap/1.0.2:
    dev: false
    resolution:
      integrity: sha1-8FKijacOYYkX7wqKw0wa5aaChrM=
  /shebang-command/1.2.0:
    dependencies:
      shebang-regex: 1.0.0
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-RKrGW2lbAzmJaMOfNj/uXer98eo=
  /shebang-regex/1.0.0:
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-2kL0l0DAtC2yypcoVxyxkMmO/qM=
  /signal-exit/3.0.2:
    dev: false
    resolution:
      integrity: sha1-tf3AjxKH6hF4Yo5BXiUTK3NkbG0=
  /source-map-support/0.5.9:
    dependencies:
      buffer-from: 1.1.1
      source-map: 0.6.1
    dev: false
    resolution:
      integrity: sha512-gR6Rw4MvUlYy83vP0vxoVNzM6t8MUXqNuRsuBmBHQDu1Fh6X015FrLdgoDKcNdkwGubozq0P4N0Q37UyFVr1EA==
  /source-map/0.6.1:
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha512-UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==
  /strip-eof/1.0.0:
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-u0P/VZim6wXYm1n80SnJgzE2Br8=
  /supports-color/5.5.0:
    dependencies:
      has-flag: 3.0.0
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha512-QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==
  /ts-node/7.0.1:
    dependencies:
      arrify: 1.0.1
      buffer-from: 1.1.1
      diff: 3.5.0
      make-error: 1.3.5
      minimist: 1.2.0
      mkdirp: 0.5.1
      source-map-support: 0.5.9
      yn: 2.0.0
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-BVwVbPJRspzNh2yfslyT1PSbl5uIk03EZlb493RKHN4qej/D06n1cEhjlOJG69oFsE7OT8XjpTUcYf6pKTLMhw==
  /typescript/3.1.6:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-tDMYfVtvpb96msS1lDX9MEdHrW4yOuZ4Kdc4Him9oU796XldPYF/t2+uKoX0BBa0hXXwDlqYQbXY5Rzjzc5hBA==
  /which/1.3.1:
    dependencies:
      isexe: 2.0.0
    dev: false
    hasBin: true
    resolution:
      integrity: sha512-HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==
  /yallist/2.1.2:
    dev: false
    resolution:
      integrity: sha1-HBH5IY8HYImkfdUS+TxmmaaoHVI=
  /yn/2.0.0:
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-5a2ryKz0CPY4X8dklWhMiOavaJo=
  'file:projects/shack.tgz':
    dev: false
    name: '@rush-temp/shack'
    resolution:
      integrity: sha512-6Fygjow6UAp7uLsVKz3U27bwmx2Uef7rgBmzRgyK51SwMF1HOYtBBQsBW0E8YrAMh+AS6z3s/3ke1d4soA0Qyg==
      tarball: 'file:projects/shack.tgz'
    version: 0.0.0
registry: 'https://registry.npmjs.org/'
shrinkwrapMinorVersion: 9
shrinkwrapVersion: 3
specifiers:
  '@rush-temp/shack': 'file:./projects/shack.tgz'
  prettier: 1.15.2
  pretty-quick: 1.8.0
  ts-node: 7.0.1
  typescript: 3.1.6
